window.esdocSearchIndex = [
  [
    "wal/src/log-index-file.js~logindexfile",
    "class/src/log-index-file.js~LogIndexFile.html",
    "<span>LogIndexFile</span> <span class=\"search-result-import-path\">wal/src/log-index-file.js</span>",
    "class"
  ],
  [
    "wal/src/queue.js~queue",
    "class/src/queue.js~Queue.html",
    "<span>Queue</span> <span class=\"search-result-import-path\">wal/src/queue.js</span>",
    "class"
  ],
  [
    "wal/src/write-ahead-log.js~writeaheadlog",
    "class/src/write-ahead-log.js~WriteAheadLog.html",
    "<span>WriteAheadLog</span> <span class=\"search-result-import-path\">wal/src/write-ahead-log.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/log-index-file.js",
    "file/src/log-index-file.js.html",
    "src/log-index-file.js",
    "file"
  ],
  [
    "src/log-index-file.js~logindexfile#baseindex",
    "class/src/log-index-file.js~LogIndexFile.html#instance-get-baseIndex",
    "src/log-index-file.js~LogIndexFile#baseIndex",
    "member"
  ],
  [
    "src/log-index-file.js~logindexfile#close",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-close",
    "src/log-index-file.js~LogIndexFile#close",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#commit",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-commit",
    "src/log-index-file.js~LogIndexFile#commit",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#commithead",
    "class/src/log-index-file.js~LogIndexFile.html#instance-get-commitHead",
    "src/log-index-file.js~LogIndexFile#commitHead",
    "member"
  ],
  [
    "src/log-index-file.js~logindexfile#constructor",
    "class/src/log-index-file.js~LogIndexFile.html#instance-constructor-constructor",
    "src/log-index-file.js~LogIndexFile#constructor",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#get",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-get",
    "src/log-index-file.js~LogIndexFile#get",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#getrange",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-getRange",
    "src/log-index-file.js~LogIndexFile#getRange",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#globalizeindex",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-globalizeIndex",
    "src/log-index-file.js~LogIndexFile#globalizeIndex",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#head",
    "class/src/log-index-file.js~LogIndexFile.html#instance-get-head",
    "src/log-index-file.js~LogIndexFile#head",
    "member"
  ],
  [
    "src/log-index-file.js~logindexfile#increment",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-increment",
    "src/log-index-file.js~LogIndexFile#increment",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#iscommitted",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-isCommitted",
    "src/log-index-file.js~LogIndexFile#isCommitted",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#localizeindex",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-localizeIndex",
    "src/log-index-file.js~LogIndexFile#localizeIndex",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#marker",
    "class/src/log-index-file.js~LogIndexFile.html#instance-get-marker",
    "src/log-index-file.js~LogIndexFile#marker",
    "member"
  ],
  [
    "src/log-index-file.js~logindexfile#name",
    "class/src/log-index-file.js~LogIndexFile.html#instance-get-name",
    "src/log-index-file.js~LogIndexFile#name",
    "member"
  ],
  [
    "src/log-index-file.js~logindexfile#offset",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-offset",
    "src/log-index-file.js~LogIndexFile#offset",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#open",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-open",
    "src/log-index-file.js~LogIndexFile#open",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#truncate",
    "class/src/log-index-file.js~LogIndexFile.html#instance-method-truncate",
    "src/log-index-file.js~LogIndexFile#truncate",
    "method"
  ],
  [
    "src/log-index-file.js~logindexfile#writable",
    "class/src/log-index-file.js~LogIndexFile.html#instance-get-writable",
    "src/log-index-file.js~LogIndexFile#writable",
    "member"
  ],
  [
    "src/queue.js",
    "file/src/queue.js.html",
    "src/queue.js",
    "file"
  ],
  [
    "src/queue.js~queue#constructor",
    "class/src/queue.js~Queue.html#instance-constructor-constructor",
    "src/queue.js~Queue#constructor",
    "method"
  ],
  [
    "src/queue.js~queue#dequeue",
    "class/src/queue.js~Queue.html#instance-method-dequeue",
    "src/queue.js~Queue#dequeue",
    "method"
  ],
  [
    "src/queue.js~queue#enqueue",
    "class/src/queue.js~Queue.html#instance-method-enqueue",
    "src/queue.js~Queue#enqueue",
    "method"
  ],
  [
    "src/queue.js~queue#isempty",
    "class/src/queue.js~Queue.html#instance-get-isEmpty",
    "src/queue.js~Queue#isEmpty",
    "member"
  ],
  [
    "src/queue.js~queue#length",
    "class/src/queue.js~Queue.html#instance-get-length",
    "src/queue.js~Queue#length",
    "member"
  ],
  [
    "src/queue.js~queue#peek",
    "class/src/queue.js~Queue.html#instance-method-peek",
    "src/queue.js~Queue#peek",
    "method"
  ],
  [
    "src/write-ahead-log.js",
    "file/src/write-ahead-log.js.html",
    "src/write-ahead-log.js",
    "file"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#close",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-close",
    "src/write-ahead-log.js~WriteAheadLog#close",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#commit",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-commit",
    "src/write-ahead-log.js~WriteAheadLog#commit",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#commithead",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-get-commitHead",
    "src/write-ahead-log.js~WriteAheadLog#commitHead",
    "member"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#constructor",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-constructor-constructor",
    "src/write-ahead-log.js~WriteAheadLog#constructor",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#index",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-get-index",
    "src/write-ahead-log.js~WriteAheadLog#index",
    "member"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#iscommitted",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-isCommitted",
    "src/write-ahead-log.js~WriteAheadLog#isCommitted",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#name",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-get-name",
    "src/write-ahead-log.js~WriteAheadLog#name",
    "member"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#next",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-get-next",
    "src/write-ahead-log.js~WriteAheadLog#next",
    "member"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#read",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-read",
    "src/write-ahead-log.js~WriteAheadLog#read",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#readrange",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-readRange",
    "src/write-ahead-log.js~WriteAheadLog#readRange",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#recover",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-recover",
    "src/write-ahead-log.js~WriteAheadLog#recover",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#size",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-get-size",
    "src/write-ahead-log.js~WriteAheadLog#size",
    "member"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#truncate",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-truncate",
    "src/write-ahead-log.js~WriteAheadLog#truncate",
    "method"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#writable",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-get-writable",
    "src/write-ahead-log.js~WriteAheadLog#writable",
    "member"
  ],
  [
    "src/write-ahead-log.js~writeaheadlog#write",
    "class/src/write-ahead-log.js~WriteAheadLog.html#instance-method-write",
    "src/write-ahead-log.js~WriteAheadLog#write",
    "method"
  ]
]